import type { Post } from "./post.types";

export const MOCK_POSTS: Post[] = [
  {
    id: "1",
    author: { id: "u1", nickname: "의젓한 토끼" },
    content: "세상에는 두 종류의 고통이 있다. 너를 아프게 하는 고통과 너를 변하게하는 고통",
    book: { title: "아픔이 길이 되려면", author: "김승섭" },
    date: "26, Monday",
    mood: "good",
    emotionTag: "# 아주 기분 좋아요",
    toneTag: "# 공감해주는 문장",
    isBookmarked: false,
    createdAt: "1분 전",
  },
  {
    id: "2",
    author: { id: "u2", nickname: "조용한 고양이" },
    content: "세상에는 두 종류의 고통이 있다.",
    book: { title: "아픔이 길이 되려면", author: "김승섭" },
    date: "25, Sunday",
    mood: "mid",
    emotionTag: "# 꽤 괜찮아요",
    toneTag: "# 공감해주는 문장",
    isBookmarked: true,
    createdAt: "3분 전",
  },
  {
    id: "3",
    author: { id: "u3", nickname: "느긋한 거북이" },
    content: "세상에는 두 종류의 고통이 있다.",
    book: { title: "아픔이 길이 되려면", author: "김승섭" },
    date: "24, Saturday",
    mood: "bad",
    emotionTag: "# 약간 별로에요",
    toneTag: "# 공감해주는 문장",
    isBookmarked: false,
    createdAt: "10분 전",
  },
  {
    id: "4",
    author: { id: "u1", nickname: "의젓한 토끼" },
    content: "세상에는 두 종류의 고통이 있다.",
    book: { title: "하루 한 장 나의 어휘력을 위한 필사 노트", author: "유성관" },
    date: "23, Friday",
    mood: "good",
    emotionTag: "# 아주 기분 좋아요",
    toneTag: "# 관점을 전환하는 문장",
    isBookmarked: false,
    createdAt: "1시간 전",
  },
];
